In [4]:
import numpy as np
test = np.array([1,2,3])
test
test2 = np.array([[1,2,3],[4,5,6]])
test2   # array([[1, 2, 3],
       #        [4, 5, 6]])
test3 = np.array([1,2,3,4,5], ndmin = 2)
test3 # array([[1, 2, 3, 4, 5]])

array([[1, 2, 3, 4, 5]])

In [8]:
test.shape  # (3,)
test2.shape # (2, 3)
test3.shape # (1, 5)

(1, 5)

In [10]:
test4 = np.array([[1,2,3], [4,5,6]])
test4.shape # (2, 3)

(2, 3)

In [14]:
test5 = test4.reshape(3,2)
test5
# array([[1, 2],
#       [3, 4],
#       [5, 6]])


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
test6 = np.arange(10)
test6 # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])



array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
test6[0] # 0
test6[:5] # array([0, 1, 2, 3, 4])
test6[-1] # 9
test6[1:-1] # array([1, 2, 3, 4, 5, 6, 7, 8])
test6[0:] # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
test6.shape # (10,)

(10,)

In [33]:
test7 = np.array([[1,2,3], [4,5,6], [7,8,9]])
test7.shape # (3,3)
test7[1] # array([4, 5, 6])
test7[0,2] # 3
test7[1:] # array([[4, 5, 6],
                 # [7, 8, 9]])
test7[1,1] # 5
test7[:,1] # array([2, 5, 8])
test7[-1,:] # array([7, 8, 9])    [rows, cols]
test7[:, [0,2]] # array([[1, 3],
                       # [4, 6],
                       # [7, 9]])


array([[1, 3],
       [4, 6],
       [7, 9]])

In [36]:
test8 = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.amin(test8) # 1    최소값
np.amin(test8, 1) # array([1, 4, 7])     1은 세로축  rows
np.amin(test8, 0) # array([1, 2, 3])     0은 가로축  cols


array([1, 2, 3])

In [40]:
np.amax(test8) # 9
np.amax(test8, 1) # array([3, 6, 9])
np.amax(test8, 0) # array([7, 8, 9])

array([7, 8, 9])

In [42]:
# ptp     min ~ max
np.ptp(test8) # 8     min ~ max

8

In [50]:
np.percentile(test8, 50)   # 5.0
np.percentile(test8, 50, 1) # array([2., 5., 8.])
np.percentile(test8, 50, 0) # array([4., 5., 6.])
np.percentile(test8, 0) # 1.0
np.percentile(test8, 0, 0) # array([1., 2., 3.])

array([1., 2., 3.])

In [53]:
# median 중간 값 
#중간값이란 여러 값을 오름차순이나 내림차순으로 늘어놓았을 때, 맨 가운데 있는 값을 말한다.
#값들의 개수가 짝수라면 가운데 두 값의 산술평균을 중간값으로 정한다.

np.median(test8) # 5.0
np.median(test8, 1) # array([2., 5., 8.])
np.median(test8, 0) # array([4., 5., 6.])


array([4., 5., 6.])

In [78]:
# mean   산술평균
# 수학과 통계학에서 산술 평균(算術平均, arithmetic mean)은 주어진 수의 합을 수의 개수로 나눈 값이다.
np.mean(test8) # 5.0
np.mean(test8, 0) # array([4., 5., 6.])

array([4., 5., 6.])

In [57]:
# average   가중산술평균
# 가중 산술 평균은 자료의 평균을 구할 때
# 자료 값의 중요도나 영향 정도에 해당하는 가중치를 반영하여 구한 평균값이다.
np.average(test8) # 5.0

5.0

In [58]:
# std   표준편차
np.std(test8) # 2.581988897471611

2.581988897471611

In [64]:
data = [1,2,3,4]
np.mean(data) # 2.5
np.std(data) # 1.118033988749895
np.median(data) # 2.5
np.average(data) # 2.5
np.var(data) # 1.25

1.25

In [77]:
data1 = [1,2,3,4,5,5,7,8,9,10,15,18,20,105,671,1025,1233,1566,11662,17673]
np.mean(data1)      # 1702.1                        산술평균
np.std(data1)       # 4449.045649349981             표준편차
np.median(data1)    # 12.5                          중간값
np.average(data1)   # 1702.1                        가중산술평균
np.var(data1)       # 19794007.189999998            분산

19794007.189999998

In [67]:
import statistics
test_data = [5,2,5,6,1,1,2,5,7,8]

In [72]:
statistics.mean(test_data)     # 4.2      평균
statistics.median(test_data)   # 5.0     중간값
statistics.stdev(test_data)    # 2.5298221281347035
statistics.variance(test_data) # 6.4
statistics.mode(test_data)     # 5

5