In [9]:
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_val_score

import pandas as pd
import numpy as np

In [10]:
data = pd.read_csv("C:\MyPython\csv\Diabetes.csv")
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [11]:
data2 = data[(data.BloodPressure != 0) & (data.BMI !=0) & (data.Glucose != 0)]

In [12]:
data2.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1

In [13]:
feature_name = ['Pregnancies', 'Glucose', 'BMI', 'DiabetesPedigreeFunction']   

In [27]:
x = data2[feature_name]
y = data2.Outcome

type(x), type(y)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [15]:
logreg = LogisticRegression()

In [16]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.3, random_state = 0)

In [17]:
logreg.fit(xtrain, ytrain)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [18]:
rResult = logreg.predict(xtest)
accuracy = metrics.accuracy_score(ytest, rResult)
accuracy           # 0.7752293577981652

# K-Fold Cross Valdiation


0.7752293577981652

In [20]:
cross_val_score(logreg, x, y, cv = 10, scoring = 'accuracy').mean()    # 0.7805877119643279

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs

0.7805877119643279

In [22]:
cmData = metrics.confusion_matrix(ytest, rResult)
cmData
# array([[123,  21],
#       [ 28,  46]], dtype=int64)


#                Non Diabetic    Diabetic
# Non Diabetic            123          21
# Diabetic                 28          46

array([[123,  21],
       [ 28,  46]], dtype=int64)

In [24]:
import plot_confusion_matrix



Confusion matrix

Example of confusion matrix usage to evaluate the quality
of the output of a classifier on the iris data set. The
diagonal elements represent the number of points for which
the predicted label is equal to the true label, while
off-diagonal elements are those that are mislabeled by the
classifier. The higher the diagonal values of the confusion
matrix the better, indicating many correct predictions.

The figures show the confusion matrix with and without
normalization by class support size (number of elements
in each class). This kind of normalization can be
interesting in case of class imbalance to have a more
visual interpretation of which class is being misclassified.

Here the results are not as good as they could be as our
choice for the regularization parameter C was not the best.
In real life applications this parameter is usually chosen
using :ref:`grid_search`.


Confusion matrix, without normalization
[[13  0  0]
 [ 0 10  6]
 [ 0  0  9]]
Normalized confusion

<Figure size 640x480 with 2 Axes>

<Figure size 640x480 with 2 Axes>

In [25]:
array([[123, 21],
      [28, 46]], dtype = int64)

NameError: name 'array' is not defined